[package]
name = "governance"
version = "1.0.0"
authors = []

[addresses]
owner_addr = "0x43a83959e6fe5a22f2262cfaed75830c34be8c2091be5c01476c89180af7a211"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]