[package]
name = "Governance"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
std = "_"
aptos_framework = "0x1"
aptos_std = "0x1"
Extensions = "0x1"
myaddr = "0x66882b8bf7f4c93a76120f77438b16cba049fe8b2e9946ca50821d70a6ee1453"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"


[dev-dependencies]

 

